---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: full_access_cluster_role_binding
rules:
- apiGroups: ["*"]
  resources: ["*"] #alternatively you can specify the resources (pods, services, secrets, configmaps, deployments etc) that you want this role to have access to
  verbs: ["*"] #you can also specify verbs like get, list, watch etc 

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full_access_cluster_role_binding
subjects:
- kind: Group
  name: full_access
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: full_access
  apiGroup: rbac.authorization.k8s.io
